---
stages:
  - build-api
  - build-frontend
  - trigger-stages

build-api:
  stage: build-api
  image:
    name: gcr.io/kaniko-project/executor:v1.20.1-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/api"
      --dockerfile "${CI_PROJECT_DIR}/api/Dockerfile"
      --build-arg "IMAGE_VERSION=${CI_COMMIT_TAG}"
      --destination "${CI_REGISTRY_IMAGE}/api:${CI_COMMIT_TAG}"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-dev$/'

build-frontend:
  stage: build-frontend
  image:
    name: gcr.io/kaniko-project/executor:v1.20.1-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --build-arg "IMAGE_VERSION=${CI_COMMIT_TAG}"
      --build-arg "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}"
      --build-arg "NEXT_PUBLIC_BROWSER_API=${NEXT_PUBLIC_BROWSER_API}"
      --build-arg "NEXT_PUBLIC_DEBUG=${NEXT_PUBLIC_DEBUG}"
      --build-arg "NEXT_PUBLIC_CDN=${NEXT_PUBLIC_CDN}"
      --destination "${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_TAG}"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-dev$/'

trigger-stages:
  stage: trigger-stages
  trigger:
    project: tekkom/infrastructure/mend-renovate/mend-renovate-bot
    strategy: depend
    branch: main
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-dev$/'
